# Generated by Django 5.2.17 on 2026-09-26 13:28

import apps.core.hotel
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("seq", models.PositiveBigIntegerField()),
                ("action", models.CharField(max_length=64)),
                ("entity", models.CharField(max_length=64)),
                ("entity_id", models.CharField(blank=True, max_length=64)),
                (
                    "before",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "after",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                ("at", models.DateTimeField()),
                ("prev_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["seq"],
                "indexes": [
                    models.Index(
                        fields=["entity", "entity_id"],
                        name="audit_audit_entity_8edb54_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hotel_id", "seq"), name="audit_seq_per_hotel"
                    )
                ],
            },
        ),
    ]
