# Generated by Django 5.2.17 on 2026-09-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_failed_attempts_user_locked_until_loginevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_password',
            field=models.BooleanField(default=False, help_text="Still the install's default password (the login page shows it; a reminder after login)."),
        ),
    ]
