# Generated by Django 5.2.17 on 2026-09-28 08:55

from django.contrib.auth.hashers import check_password
from django.db import migrations, models

DEFAULT_PIN = "123456"  # accounts.rules.DEFAULT_PIN when this migration was written


def flag_default_pins(apps, schema_editor):
    """Accounts that still sign in with the well-known PIN get the reminder (review 2026-09-28, SEC-3)."""
    User = apps.get_model("accounts", "User")
    ids = [pk for pk, pin_hash in User.objects.values_list("pk", "pin_hash") if pin_hash and check_password(DEFAULT_PIN, pin_hash)]
    User.objects.filter(pk__in=ids).update(default_pin=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_default_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_pin',
            field=models.BooleanField(default=False, help_text='The quick-login PIN is the well-known default (123456): anyone can pick the account and type it.'),
        ),
        migrations.RunPython(flag_default_pins, migrations.RunPython.noop),
    ]
