# Generated by Django 5.2.17 on 2026-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_default_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Reference email: «نسيت كلمة المرور؟» on the reception PC asks for it (offline, nothing is sent).', max_length=254),
        ),
    ]
