# Generated by Django 5.2.17 on 2026-09-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemClock",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("clock_blocked", models.BooleanField(default=False)),
                (
                    "blocked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Device time when the rollback was detected.",
                        null=True,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="system_clock_singleton"
                    )
                ],
            },
        ),
    ]
