# Generated by Django 5.2.17 on 2026-09-26 13:57

import apps.core.fields
import apps.core.hotel
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "name_ar",
                    models.CharField(default="فندق سكاي تاورز", max_length=120),
                ),
                (
                    "name_latin",
                    models.CharField(default="Sky Towers Hotel", max_length=120),
                ),
                ("address", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "currency",
                    models.CharField(default="SDG", editable=False, max_length=10),
                ),
                (
                    "digits",
                    models.CharField(
                        choices=[("western", "123"), ("arabic", "١٢٣")],
                        default="western",
                        max_length=10,
                    ),
                ),
                (
                    "money_decimals",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="0 or 2 decimals when showing money."
                    ),
                ),
                (
                    "stay_day_end",
                    models.TimeField(
                        default="23:59",
                        help_text="A stay becomes overdue after this time.",
                    ),
                ),
                ("session_lock_minutes", models.PositiveSmallIntegerField(default=15)),
                (
                    "expense_attachment_threshold",
                    apps.core.fields.MoneyField(
                        default=2000000,
                        help_text="Receipt required above (minor units).",
                    ),
                ),
                ("max_discount_percent", models.PositiveSmallIntegerField(default=20)),
                ("auto_print_receipt", models.BooleanField(default=True)),
                ("thermal_printer", models.CharField(blank=True, max_length=60)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hotel_id",), name="one_settings_row_per_hotel"
                    )
                ],
            },
        ),
    ]
