# Generated by Django 5.2.17 on 2026-09-26 15:00

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_hotelsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelsettings",
            name="debt_attention_threshold",
            field=apps.core.fields.MoneyField(
                default=5000000, help_text="Owner dashboard: debts above this (minor)."
            ),
        ),
    ]
