# Generated by Django 5.2.17 on 2026-09-26 14:16

import apps.core.fields
import apps.core.hotel
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cash", "0002_expense_number_expense_expense_number_per_hotel"),
        ("rooms", "0001_initial"),
        ("stays", "0002_stay_staysegment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=80)),
                (
                    "trigger_kind",
                    models.CharField(
                        choices=[
                            ("stay_ending", "انتهاء الإقامة"),
                            ("stay_overdue", "إقامة متجاوزة"),
                            ("checkout_debt", "خروج بدين"),
                            ("shift_open_too_long", "وردية مفتوحة طويلًا"),
                            ("room_cleaning_too_long", "تنظيف متأخر"),
                            ("room_maintenance_too_long", "صيانة طويلة"),
                            ("no_backup", "لا نسخة احتياطية"),
                            ("no_drive_upload", "لا رفع إلى Drive"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "duration_kind",
                    models.CharField(
                        blank=True,
                        help_text="stay_ending: daily / weekly / monthly.",
                        max_length=10,
                    ),
                ),
                ("days_before", models.PositiveSmallIntegerField(default=0)),
                (
                    "second_days_before",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("at_time", models.TimeField(default="09:00")),
                (
                    "repeat_hours",
                    models.PositiveSmallIntegerField(
                        default=12, help_text="0 = no repeat."
                    ),
                ),
                ("max_snoozes", models.PositiveSmallIntegerField(default=3)),
                (
                    "escalate_after_hours",
                    models.PositiveSmallIntegerField(
                        default=24, help_text="Open this long → neglected."
                    ),
                ),
                (
                    "threshold_hours",
                    models.PositiveIntegerField(
                        blank=True, help_text="shift/room/backup triggers.", null=True
                    ),
                ),
                (
                    "threshold",
                    apps.core.fields.MoneyField(
                        blank=True,
                        help_text="checkout_debt: balance above this (minor units).",
                        null=True,
                    ),
                ),
                ("windows_notification", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["trigger_kind", "duration_kind"],
            },
        ),
        migrations.CreateModel(
            name="FollowupTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "subject_key",
                    models.CharField(
                        help_text="stay:<id> / room:<id> / shift:<id>", max_length=80
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("due_at", models.DateTimeField()),
                ("due_date", models.DateField()),
                ("second_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "مفتوحة"),
                            ("snoozed", "مؤجلة"),
                            ("waiting", "بانتظار الرد"),
                            ("done", "منجزة"),
                            ("superseded", "مستبدلة"),
                            ("neglected", "مُهمَلة"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("snooze_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When a snoozed/waiting task comes back.",
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Latest «بانتظار الرد» note.",
                        max_length=300,
                    ),
                ),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("neglected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rooms.room",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="followups.alertrule",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subject shift, or the shift that was open when the task became neglected.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cash.shift",
                    ),
                ),
                (
                    "stay",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="stays.stay",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("extend", "تمديد"),
                            ("confirm_checkout", "تأكيد المغادرة"),
                            ("waiting", "بانتظار الرد"),
                            ("snooze", "تأجيل"),
                            ("done", "تم"),
                        ],
                        max_length=20,
                    ),
                ),
                ("at", models.DateTimeField()),
                ("note", models.CharField(blank=True, max_length=300)),
                ("next_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cash.shift",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="followups.followuptask",
                    ),
                ),
            ],
            options={
                "ordering": ["at"],
            },
        ),
        migrations.CreateModel(
            name="Toast",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "seq",
                    models.PositiveBigIntegerField(
                        db_index=True, help_text="Poll cursor."
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("body", models.CharField(max_length=120)),
                ("at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="toasts",
                        to="followups.followuptask",
                    ),
                ),
            ],
            options={
                "ordering": ["seq"],
            },
        ),
        migrations.AddIndex(
            model_name="followuptask",
            index=models.Index(
                fields=["status", "due_at"], name="followups_f_status_9e5de0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="followuptask",
            constraint=models.UniqueConstraint(
                fields=("rule", "subject_key", "due_date"),
                name="task_once_per_rule_subject_day",
            ),
        ),
    ]
