# Generated by Django 5.2.17 on 2026-09-26 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash", "0002_expense_number_expense_expense_number_per_hotel"),
        ("followups", "0001_initial"),
        ("rooms", "0001_initial"),
        ("stays", "0002_stay_staysegment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="followuptask",
            name="task_once_per_rule_subject_day",
        ),
        migrations.AddConstraint(
            model_name="followuptask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "superseded"), _negated=True),
                fields=("rule", "subject_key", "due_date"),
                name="task_once_per_rule_subject_day",
            ),
        ),
    ]
