# Generated by Django 5.2.17 on 2026-09-29 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_date_indexes'),
        ('followups', '0002_task_unique_ignores_superseded'),
        ('rooms', '0002_room_name'),
        ('stays', '0002_stay_staysegment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['due_at'], name='followups_f_due_at_7b4f2d_idx'),
        ),
    ]
