# Generated by Django 5.2.17 on 2026-09-26 13:57

import apps.core.fields
import apps.core.hotel
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stays", "0002_stay_staysegment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_id", models.UUIDField()),
                ("name", models.CharField(max_length=20)),
                ("last", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Folio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("invoice_no", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "مفتوحة"), ("closed", "مغلقة")],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="folio",
                        to="stays.reservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_no"],
            },
        ),
        migrations.CreateModel(
            name="FolioLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("room", "إقامة"),
                            ("service", "خدمة"),
                            ("discount", "خصم"),
                            ("adjustment", "تسوية"),
                            ("tax", "ضريبة"),
                            ("reversal", "عكس"),
                        ],
                        max_length=12,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "amount",
                    apps.core.fields.MoneyField(
                        help_text="Signed minor units: charges +, discounts/credits −."
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("posted_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="billing.folio",
                    ),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="billing.folioline",
                    ),
                ),
            ],
            options={
                "ordering": ["posted_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deposit", "عربون"),
                            ("payment", "دفعة"),
                            ("refund", "ردّ"),
                            ("reversal", "عكس دفعة"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدي"),
                            ("bankak", "بنكك"),
                            ("transfer", "تحويل"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    apps.core.fields.MoneyField(
                        help_text="Signed minor units: received +, refunded/reversed −."
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Bankak / transfer reference.",
                        max_length=60,
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Non-cash reference checked against the bank app.",
                    ),
                ),
                ("receipt_no", models.PositiveIntegerField()),
                ("reason", models.CharField(blank=True, max_length=300)),
                ("received_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.folio",
                    ),
                ),
                (
                    "reverses",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_by",
                        to="billing.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["received_at", "created_at"],
            },
        ),
    ]
