# Generated by Django 5.2.17 on 2026-09-26 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("cash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="cash.shift",
            ),
        ),
        migrations.AddConstraint(
            model_name="sequence",
            constraint=models.UniqueConstraint(
                fields=("hotel_id", "name"), name="sequence_per_hotel"
            ),
        ),
        migrations.AddConstraint(
            model_name="folio",
            constraint=models.UniqueConstraint(
                fields=("hotel_id", "invoice_no"), name="invoice_no_per_hotel"
            ),
        ),
        migrations.AddConstraint(
            model_name="folioline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="folio_line_not_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount", 0), _negated=True),
                name="payment_not_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("hotel_id", "receipt_no"), name="receipt_no_per_hotel"
            ),
        ),
    ]
