# Generated by Django 5.2.17 on 2026-09-28 15:05

import apps.core.fields
import apps.core.hotel
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, help_text='Empty: the base currency; else ISO code (USD).', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='foreign_amount',
            field=models.BigIntegerField(blank=True, help_text='Signed minor units (cents) of currency.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate',
            field=models.BigIntegerField(blank=True, help_text='Base minor units per whole unit, at the time.', null=True),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_id', models.UUIDField(db_index=True, default=apps.core.hotel.current_hotel_id)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(help_text='ISO 4217, e.g. USD.', max_length=3)),
                ('name', models.CharField(max_length=40)),
                ('symbol', models.CharField(blank=True, max_length=6)),
                ('rate', apps.core.fields.MoneyField(help_text='Base-currency minor units for one whole unit of this currency.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('hotel_id', 'code'), name='currency_code_per_hotel'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='currency_rate_positive')],
            },
        ),
    ]
