# Generated by Django 5.2.17 on 2026-09-29 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_currencies'),
        ('cash', '0003_date_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='folioline',
            index=models.Index(fields=['posted_at'], name='billing_fol_posted__6f9be6_idx'),
        ),
        migrations.AddIndex(
            model_name='folioline',
            index=models.Index(fields=['folio', 'amount'], name='billing_fol_folio_i_d6838f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['received_at'], name='billing_pay_receive_c24998_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['folio', 'amount'], name='billing_pay_folio_i_5dd2f7_idx'),
        ),
    ]
