# Generated by Django 5.2.17 on 2026-09-26 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash", "0001_initial"),
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="number",
            field=models.PositiveIntegerField(
                help_text="Gap-free per hotel; printed as EXP-000123.", null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.UniqueConstraint(
                fields=("hotel_id", "number"), name="expense_number_per_hotel"
            ),
        ),
    ]
