# Generated by Django 5.2.17 on 2026-09-29 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_expense_number_expense_expense_number_per_hotel'),
        ('rooms', '0002_room_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['spent_at'], name='cash_expens_spent_a_8f8b51_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['opened_at'], name='cash_shift_opened__7b4198_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['closed_at'], name='cash_shift_closed__693bac_idx'),
        ),
    ]
