# Generated by Django 5.2.17 on 2026-09-29 11:28

import apps.core.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_date_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='counted_foreign',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shift',
            name='expected_foreign',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shift',
            name='handed_over',
            field=apps.core.fields.MoneyField(default=0, help_text='Pounds taken out at close (to the owner or the safe).'),
        ),
        migrations.AddField(
            model_name='shift',
            name='handed_over_foreign',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shift',
            name='opening_expected',
            field=apps.core.fields.MoneyField(blank=True, help_text='Left in the drawer by the previous shift.', null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='opening_foreign',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shift',
            name='opening_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('handed_over__gte', 0)), name='shift_handed_over_not_negative'),
        ),
    ]
