# Generated by Django 5.2.17 on 2026-09-26 13:33

import apps.core.fields
import apps.core.hotel
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=40)),
                ("capacity", models.PositiveSmallIntegerField(default=1)),
                ("nightly_price", apps.core.fields.MoneyField()),
                ("weekly_price", apps.core.fields.MoneyField(help_text="7 nights")),
                ("monthly_price", apps.core.fields.MoneyField(help_text="30 nights")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nightly_price", "name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("number", models.CharField(max_length=10)),
                ("floor", models.SmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "جاهزة"),
                            ("occupied", "مشغولة"),
                            ("cleaning", "تحتاج تنظيف"),
                            ("maintenance", "صيانة"),
                        ],
                        default="ready",
                        max_length=16,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("maintenance_reason", models.CharField(blank=True, max_length=200)),
                ("in_service", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms",
                        to="rooms.roomtype",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="RoomStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("ready", "جاهزة"),
                            ("occupied", "مشغولة"),
                            ("cleaning", "تحتاج تنظيف"),
                            ("maintenance", "صيانة"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("ready", "جاهزة"),
                            ("occupied", "مشغولة"),
                            ("cleaning", "تحتاج تنظيف"),
                            ("maintenance", "صيانة"),
                        ],
                        max_length=16,
                    ),
                ),
                ("at", models.DateTimeField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_history",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "ordering": ["-at"],
                "indexes": [
                    models.Index(
                        fields=["room", "at"], name="rooms_rooms_room_id_ecfaad_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="roomtype",
            constraint=models.UniqueConstraint(
                fields=("hotel_id", "name"), name="room_type_name_per_hotel"
            ),
        ),
        migrations.AddConstraint(
            model_name="roomtype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("monthly_price__gte", 0),
                    ("nightly_price__gte", 0),
                    ("weekly_price__gte", 0),
                ),
                name="room_type_prices_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("hotel_id", "number"), name="room_number_per_hotel"
            ),
        ),
    ]
