LangString addOrReinstall ${LANG_ARABIC} "إضافة المكوّنات أو إعادة التثبيت"
LangString alreadyInstalled ${LANG_ARABIC} "البرنامج مثبّت من قبل"
LangString alreadyInstalledLong ${LANG_ARABIC} "الإصدار ${VERSION} من ${PRODUCTNAME} مثبّت على هذا الجهاز. اختر ما تريد ثم اضغط «التالي»."
LangString appRunning ${LANG_ARABIC} "نافذة ${PRODUCTNAME} مفتوحة الآن. أغلقها (ومن أيقونتها بجانب الساعة اختر «خروج») ثم أعد المحاولة."
LangString appRunningOkKill ${LANG_ARABIC} "نافذة ${PRODUCTNAME} مفتوحة الآن.$\nاضغط «موافق» (OK) لإغلاقها والمتابعة."
LangString chooseMaintenanceOption ${LANG_ARABIC} "اختر ما تريد فعله."
LangString choowHowToInstall ${LANG_ARABIC} "اختر طريقة تثبيت ${PRODUCTNAME}."
LangString createDesktop ${LANG_ARABIC} "إضافة أيقونة على سطح المكتب"
LangString dontUninstall ${LANG_ARABIC} "التثبيت فوق الإصدار الحالي (تبقى كل بيانات الفندق)"
LangString dontUninstallDowngrade ${LANG_ARABIC} "عدم الإزالة (غير متاح عند تثبيت إصدار أقدم)"
LangString failedToKillApp ${LANG_ARABIC} "تعذّر إغلاق نافذة ${PRODUCTNAME}. أغلقها بنفسك ثم أعد المحاولة."
LangString installingWebview2 ${LANG_ARABIC} "جارٍ تثبيت مكوّن العرض WebView2…"
LangString newerVersionInstalled ${LANG_ARABIC} "على هذا الجهاز إصدار أحدث من ${PRODUCTNAME}، وهذا الملف أقدم منه. لا داعي لتثبيته: اضغط «إلغاء»."
LangString older ${LANG_ARABIC} "أقدم"
LangString olderOrUnknownVersionInstalled ${LANG_ARABIC} "على هذا الجهاز إصدار $R4 من ${PRODUCTNAME}. اضغط «التالي» للتحديث؛ الخياران أدناه يحتفظان بكل بيانات الفندق."
LangString silentDowngrades ${LANG_ARABIC} "لا يمكن تثبيت إصدار أقدم من الإصدار المثبّت دون واجهة. شغّل الملف بالنقر عليه."
LangString unableToUninstall ${LANG_ARABIC} "تعذّرت إزالة الإصدار الحالي."
LangString uninstallApp ${LANG_ARABIC} "إزالة ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ARABIC} "إزالة الإصدار الحالي ثم التثبيت (تبقى كل بيانات الفندق)"
LangString unknown ${LANG_ARABIC} "غير معروف"
LangString webview2AbortError ${LANG_ARABIC} "تعذّر تثبيت مكوّن العرض WebView2، والبرنامج لا يعمل بدونه. أعد تشغيل ملف التثبيت."
LangString webview2DownloadError ${LANG_ARABIC} "تعذّر تنزيل مكوّن العرض WebView2 — $0"
LangString webview2DownloadSuccess ${LANG_ARABIC} "تم تنزيل مكوّن العرض WebView2."
LangString webview2Downloading ${LANG_ARABIC} "جارٍ تنزيل مكوّن العرض WebView2…"
LangString webview2InstallError ${LANG_ARABIC} "تعذّر تثبيت مكوّن العرض WebView2 (الرمز $1)."
LangString webview2InstallSuccess ${LANG_ARABIC} "تم تثبيت مكوّن العرض WebView2."
LangString deleteAppData ${LANG_ARABIC} "مسح إعدادات نافذة البرنامج (بيانات الفندق لا تُمسح)"
