# Generated by Django 5.2.17 on 2026-09-26 13:40

import apps.core.fields
import apps.core.hotel
import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guests", "0001_initial"),
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                (
                    "duration_kind",
                    models.CharField(
                        choices=[
                            ("daily", "يومي"),
                            ("weekly", "أسبوعي"),
                            ("monthly", "شهري"),
                            ("mixed", "مختلط"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "duration_count",
                    models.PositiveSmallIntegerField(
                        help_text="Units of duration_kind; nights when mixed."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "مؤكد"),
                            ("checked_in", "مسكّن"),
                            ("checked_out", "غادر"),
                            ("cancelled", "ملغى"),
                            ("no_show", "لم يحضر"),
                        ],
                        default="confirmed",
                        max_length=12,
                    ),
                ),
                (
                    "rate_snapshot",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "total",
                    apps.core.fields.MoneyField(
                        help_text="Agreed room charge in minor units (override if any, else base)."
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "status_reason",
                    models.CharField(
                        blank=True,
                        help_text="Why it was cancelled / no-show.",
                        max_length=300,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="guests.guest",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="rooms.room",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="rooms.roomtype",
                    ),
                ),
            ],
            options={
                "ordering": ["check_in_date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "status", "check_in_date"],
                        name="stays_reser_room_id_cb56eb_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("check_out_date__gt", models.F("check_in_date"))
                        ),
                        name="reservation_dates_ordered",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total__gte", 0)),
                        name="reservation_total_not_negative",
                    ),
                ],
            },
        ),
    ]
