# Generated by Django 5.2.17 on 2026-09-29 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('rooms', '0002_room_name'),
        ('stays', '0002_stay_staysegment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'check_out_date'], name='stays_reser_status_3b75b4_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['check_in_date'], name='stays_reser_check_i_e6f364_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['checked_in_at'], name='stays_stay_checked_5ee1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='stay',
            index=models.Index(fields=['checked_out_at'], name='stays_stay_checked_7ccfa9_idx'),
        ),
        migrations.AddIndex(
            model_name='staysegment',
            index=models.Index(fields=['to_date'], name='stays_stays_to_date_9efc60_idx'),
        ),
    ]
