# Generated by Django 5.2.17 on 2026-09-26 14:27

import apps.core.hotel
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manual", "يدوي"),
                            ("scheduled", "مجدول"),
                            ("shift_close", "عند الإغلاق"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "تمت"),
                            ("failed", "فشلت"),
                            ("skipped", "تخطّي"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Per-hotel backup number (ok runs only).",
                        null=True,
                    ),
                ),
                (
                    "full",
                    models.BooleanField(
                        default=False,
                        help_text="All attachments (weekly), else changed ones only.",
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=300)),
                ("second_path", models.CharField(blank=True, max_length=300)),
                ("second_error", models.CharField(blank=True, max_length=300)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                (
                    "audit_seq",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Last audit seq included; detects «no changes».",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=300)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriveUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("ok", models.BooleanField()),
                ("drive_file_id", models.CharField(blank=True, max_length=120)),
                ("message", models.CharField(blank=True, max_length=300)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploads",
                        to="backup.backuprun",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "source",
                    models.CharField(
                        choices=[("drive", "Drive"), ("file", "USB")], max_length=10
                    ),
                ),
                ("file_name", models.CharField(max_length=200)),
                ("backup_seq", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "data_as_of",
                    models.DateTimeField(
                        blank=True,
                        help_text="created_at in the imported manifest.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "اكتمل"), ("failed", "مرفوض")], max_length=10
                    ),
                ),
                ("counts", models.JSONField(default=dict)),
                (
                    "checks",
                    models.JSONField(
                        default=list,
                        help_text="[{key, label, detail, status}] — the five pre-merge checks.",
                    ),
                ),
                ("audit_chain_ok", models.BooleanField(null=True)),
                ("error", models.CharField(blank=True, max_length=300)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotel_id",
                    models.UUIDField(
                        db_index=True, default=apps.core.hotel.current_hotel_id
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "owner_recipient",
                    models.CharField(
                        blank=True,
                        help_text="Owner's age public key (age1…); backups are encrypted to it.",
                        max_length=200,
                    ),
                ),
                ("interval_hours", models.PositiveSmallIntegerField(default=6)),
                ("keep_count", models.PositiveSmallIntegerField(default=30)),
                ("on_shift_close", models.BooleanField(default=True)),
                ("auto_drive", models.BooleanField(default=True)),
                (
                    "second_dir",
                    models.CharField(
                        blank=True,
                        help_text="USB / external disk folder.",
                        max_length=260,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hotel_id",), name="one_backup_settings_per_hotel"
                    )
                ],
            },
        ),
    ]
