# Generated by Django 5.2.17 on 2026-09-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backupsettings",
            name="keep_days",
            field=models.PositiveSmallIntegerField(
                default=90, help_text="Backups older than this are deleted; 0 = never."
            ),
        ),
    ]
