# Generated by Django 5.2.17 on 2026-09-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_backup_key_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprun',
            name='slots',
            field=models.PositiveSmallIntegerField(default=0, help_text='Owner/manager key slots in the file: 0 = it opens on no other PC (default password).'),
        ),
    ]
