# Generated by Django 5.2.17 on 2026-09-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_backup_run_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='device',
            field=models.CharField(blank=True, help_text='Reception PC the backup came from (1.1.12+).', max_length=64),
        ),
    ]
