# Generated by Django 5.2.17 on 2026-09-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_import_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsettings',
            name='max_total_mb',
            field=models.PositiveIntegerField(default=5000, help_text='The backups of a folder together stay under this size (MB); 0 = no limit.'),
        ),
    ]
