// Generated by build/tokens-to-tailwind.ts from design-package/project/tokens.json — do not edit.
import type { Config } from "tailwindcss";

const preset: Partial<Config> = {
  "theme": {
    "extend": {
      "colors": {
        "bg-page": "var(--color-bg-page)",
        "bg-surface": "var(--color-bg-surface)",
        "bg-surface-2": "var(--color-bg-surface-2)",
        "border": "var(--color-border)",
        "border-strong": "var(--color-border-strong)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-disabled": "var(--color-text-disabled)",
        "primary": "var(--color-primary)",
        "primary-hover": "var(--color-primary-hover)",
        "primary-soft": "var(--color-primary-soft)",
        "primary-text-on": "var(--color-primary-text-on)",
        "success": "var(--color-success)",
        "warning": "var(--color-warning)",
        "danger": "var(--color-danger)",
        "info": "var(--color-info)",
        "owner-banner-bg": "var(--color-owner-banner-bg)",
        "owner-banner-text": "var(--color-owner-banner-text)",
        "chart-secondary": "var(--color-chart-secondary)",
        "state": {
          "ready": {
            "DEFAULT": "var(--color-state-ready)",
            "soft": "var(--color-state-ready-soft)",
            "text": "var(--color-state-ready-text)"
          },
          "occupied": {
            "DEFAULT": "var(--color-state-occupied)",
            "soft": "var(--color-state-occupied-soft)",
            "text": "var(--color-state-occupied-text)"
          },
          "cleaning": {
            "DEFAULT": "var(--color-state-cleaning)",
            "soft": "var(--color-state-cleaning-soft)",
            "text": "var(--color-state-cleaning-text)"
          },
          "maintenance": {
            "DEFAULT": "var(--color-state-maintenance)",
            "soft": "var(--color-state-maintenance-soft)",
            "text": "var(--color-state-maintenance-text)"
          },
          "overdue": {
            "DEFAULT": "var(--color-state-overdue)",
            "soft": "var(--color-state-overdue-soft)",
            "text": "var(--color-state-overdue-text)"
          },
          "reserved-soon": {
            "DEFAULT": "var(--color-state-reserved-soon)"
          }
        },
        "success-soft": "var(--color-success-soft)",
        "success-text": "var(--color-success-text)",
        "warning-soft": "var(--color-warning-soft)",
        "warning-text": "var(--color-warning-text)",
        "danger-soft": "var(--color-danger-soft)",
        "danger-text": "var(--color-danger-text)",
        "info-soft": "var(--color-info-soft)",
        "info-text": "var(--color-info-text)",
        "focus-ring": "var(--color-focus-ring)"
      },
      "fontFamily": {
        "sans": [
          "var(--font-family)"
        ]
      },
      "fontSize": {
        "page-title": [
          "20px",
          {
            "lineHeight": "28px",
            "fontWeight": "600"
          }
        ],
        "section-title": [
          "16px",
          {
            "lineHeight": "24px",
            "fontWeight": "600"
          }
        ],
        "body": [
          "14px",
          {
            "lineHeight": "22px",
            "fontWeight": "400"
          }
        ],
        "table-cell": [
          "14px",
          {
            "lineHeight": "20px",
            "fontWeight": "400"
          }
        ],
        "label": [
          "12px",
          {
            "lineHeight": "16px",
            "fontWeight": "500"
          }
        ],
        "headline-number": [
          "28px",
          {
            "lineHeight": "34px",
            "fontWeight": "700"
          }
        ],
        "room-number": [
          "22px",
          {
            "lineHeight": "28px",
            "fontWeight": "700"
          }
        ]
      },
      "borderRadius": {
        "control": "var(--radius-control)",
        "card": "var(--radius-card)",
        "modal": "var(--radius-modal)"
      },
      "boxShadow": {
        "card": "var(--shadow-card)",
        "elevated": "var(--shadow-elevated)"
      },
      "spacing": {
        "table-row": "var(--size-table-row)",
        "card-padding": "var(--size-card-padding)",
        "button": "var(--size-button)",
        "button-lg": "var(--size-button-lg)",
        "topbar": "var(--size-topbar)",
        "sidebar": "var(--size-sidebar)",
        "sidebar-rail": "var(--size-sidebar-rail)",
        "drawer": "var(--size-drawer)",
        "room-card-w": "var(--size-room-card-w)",
        "room-card-h": "var(--size-room-card-h)",
        "icon": "var(--size-icon)",
        "icon-inline": "var(--size-icon-inline)"
      },
      "width": {
        "table-row": "var(--size-table-row)",
        "card-padding": "var(--size-card-padding)",
        "button": "var(--size-button)",
        "button-lg": "var(--size-button-lg)",
        "topbar": "var(--size-topbar)",
        "sidebar": "var(--size-sidebar)",
        "sidebar-rail": "var(--size-sidebar-rail)",
        "drawer": "var(--size-drawer)",
        "room-card-w": "var(--size-room-card-w)",
        "room-card-h": "var(--size-room-card-h)",
        "icon": "var(--size-icon)",
        "icon-inline": "var(--size-icon-inline)"
      },
      "height": {
        "table-row": "var(--size-table-row)",
        "card-padding": "var(--size-card-padding)",
        "button": "var(--size-button)",
        "button-lg": "var(--size-button-lg)",
        "topbar": "var(--size-topbar)",
        "sidebar": "var(--size-sidebar)",
        "sidebar-rail": "var(--size-sidebar-rail)",
        "drawer": "var(--size-drawer)",
        "room-card-w": "var(--size-room-card-w)",
        "room-card-h": "var(--size-room-card-h)",
        "icon": "var(--size-icon)",
        "icon-inline": "var(--size-icon-inline)"
      }
    }
  }
};

export default preset;
